name: deploy

on:
  push:
    branches: ['main']

jobs:
    build:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [16.x]
    steps:
    - name: Checkout source code.
      uses: actions/checkout@v2

    - name: create env
      run: |
        touch .env
        echo "${{ secrets.DATA }}" >> .env

    - name: create remote directory # ec2 서버에 디렉토리를 하나 만들어준다.
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: mkdir -p /home/ubuntu/MSG-BackEnd-V2

    - name: copy source via ssh key # ssh key를 이용해 현재 푸시된 소스를 서버에 복사한다.
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        remote_path: /home/ubuntu/MSG-BackEnd-V2
        remote_host: ${{ secrets.HOST }}
        remote_user: ubuntu
        remote_key: ${{ secrets.SSH_KEY }}

    - name: executing remote ssh commands using password # 서버에 접속하여 deploy.sh 를 실행시킨다.
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          ****sh /home/ubuntu/sh/deploy.sh

